# Generated by Django 6.0.7 on 2026-08-01 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=30, verbose_name='物流單號')),
                ('status', models.CharField(max_length=20, verbose_name='配送狀態')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, unique=True, verbose_name='訂單編號')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='成立時間')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='買家')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.shipment', verbose_name='物流')),
            ],
        ),
    ]
